runtime: java17

env_variables:
  SPRING_PROFILES_ACTIVE: prod

beta_settings:
  cloud_sql_instances: YOUR_PROJECT_ID:YOUR_REGION:YOUR_INSTANCE_ID

automatic_scaling:
  min_instances: 1
  max_instances: 3


